# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
      with:
        # FTP host
        ftp_host: ftp.coalmentech.com
        # FTP username
        ftp_username: u233443568.coalman
        # FTP password
        ftp_password: logitech
        # The local folder to copy
        local_source_dir: dist/dcmpkl/
        # The remote folder
        dist_target_dir: /test/
        # Delete files not present in the local folder on the remote folder
        delete: false
        exclude: ("^sample.htm")
